// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajnqnvogdkjhymweaunr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqbnFudm9nZGtqaHltd2VhdW5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1OTk4NDQsImV4cCI6MjA3MTE3NTg0NH0.gyxKf8bYhdEcBRIvWQ9UrvFDhb1wjjeQBe2ndv7gZVY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});